version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:15
    container_name: matcha_db
    environment:
      POSTGRES_DB: matcha
      POSTGRES_USER: matcha_user
      POSTGRES_PASSWORD: matcha_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - matcha_network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: matcha_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - matcha_network

  # Adminer for database management
  adminer:
    image: adminer:latest
    container_name: matcha_adminer
    ports:
      - "5050:8080"
    depends_on:
      - db
    networks:
      - matcha_network

  # MailHog for email testing
  mailhog:
    image: mailhog/mailhog:latest
    container_name: matcha_mailhog
    ports:
      - "1025:1025"  # SMTP server
      - "8025:8025"  # Web UI
    networks:
      - matcha_network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: matcha_backend
    environment:
      - DATABASE_URL=postgresql+asyncpg://matcha_user:matcha_password@db:5432/matcha
      - REDIS_URL=redis://redis:6379/0
      - ENVIRONMENT=development
      - SECRET_KEY=your-secret-key-change-in-production
      - CLOUDINARY_CLOUD_NAME=your-cloudinary-name
      - CLOUDINARY_API_KEY=your-cloudinary-api-key
      - CLOUDINARY_API_SECRET=your-cloudinary-api-secret
      - SMTP_HOST=mailhog
      - SMTP_PORT=1025
      - SMTP_USER=""
      - SMTP_PASSWORD=""
      - EMAILS_FROM_EMAIL=noreply@matcha.dev
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    networks:
      - matcha_network
    restart: unless-stopped

  # Frontend (commented out - run locally with npm run dev)
  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   container_name: matcha_frontend
  #   environment:
  #     - VITE_API_URL=http://localhost:8000
  #     - VITE_WEBSOCKET_URL=ws://localhost:8000
  #   ports:
  #     - "5173:5173"
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules
  #   depends_on:
  #     - backend
  #   networks:
  #     - matcha_network
  #   command: npm run dev

volumes:
  postgres_data:
  redis_data:

networks:
  matcha_network:
    driver: bridge
