version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:15
    container_name: matcha_db
    environment:
      POSTGRES_DB: matcha
      POSTGRES_USER: matcha_user
      POSTGRES_PASSWORD: matcha_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - matcha_network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: matcha_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - matcha_network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: matcha_backend
    environment:
      - DATABASE_URL=postgresql://matcha_user:matcha_password@db:5432/matcha
      - REDIS_URL=redis://redis:6379/0
      - ENVIRONMENT=development
      - SECRET_KEY=your-secret-key-change-in-production
      - CLOUDINARY_CLOUD_NAME=your-cloudinary-name
      - CLOUDINARY_API_KEY=your-cloudinary-api-key
      - CLOUDINARY_API_SECRET=your-cloudinary-api-secret
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - /app/.venv
    depends_on:
      - db
      - redis
    networks:
      - matcha_network
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: matcha_frontend
    environment:
      - VITE_API_URL=http://localhost:8000
      - VITE_WEBSOCKET_URL=ws://localhost:8000
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - matcha_network
    command: npm run dev

volumes:
  postgres_data:
  redis_data:

networks:
  matcha_network:
    driver: bridge