"""Add has_completed_profile to users table

Revision ID: 626a29087fa9
Revises: 97fbc9e1114f
Create Date: 2025-07-22 21:53:03.524097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '626a29087fa9'
down_revision: Union[str, None] = '97fbc9e1114f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('has_completed_profile', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'has_completed_profile')
    # ### end Alembic commands ###