from typing import Protocol, TypeVar, Generic, Sequence

T = TypeVar("T")


class Repository(Generic[T], Protocol):
    async def get(self, id: str) -> T | None: ...

    async def list(self) -> Sequence[T]: ...

    async def add(self, entity: T) -> None: ...

    async def update(self, entity: T) -> None: ...

    async def delete(self, id: str) -> None: ...
